Init Libraries
mash-up-kr/KKyuni_Android pull request #2
Opened 2021-09-13 14:01 UTC by Huijiny

## Issue
- close #1 

## Overview (Required)
- 필요한 라이브러리들을 추가했습니다.
- Coroutine

## Links
-

## Screenshot
Before | After
:--: | :--:
<img src="" width="240" /> | <img src="" width="240" />

2021-09-14 02:12 UTC, lagoJin requested changes
fragment랑 activity도 implementation 추가하면 좋을 것 같습니다!
fragment 추가하실 때 alpha 버전 최신으로 부탁드릴게요 , navigation 에서 백스택 유지하는걸 지원하는 기능이 있어서요~!

2021-09-14 02:12 UTC, lagoJin commented on app/build.gradle
> +    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
logging, moshi 라이브러리도 추가하면 좋을것같아요~

2021-09-14 02:12 UTC, lagoJin commented on build.gradle
> +        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
build.gradle 에서 사용하는 버전이랑 똑같아서 kotlin, hilt version 한군데서 관리하면 좋을 것 같아요~!

2021-09-14 02:14 UTC, SEONGGYU96 commented
진호님 피드백에 동의합니다

2021-09-14 05:24 UTC, Huijiny commented on app/build.gradle
> +    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
네 알겠습니다 :)

2021-09-14 05:26 UTC, Huijiny commented on build.gradle
> +        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
앗 한군데서 관리한다는게 어느 파일에 선언해놓으라는 뜻인지 잘 모르겠어서, 혹시 관련 레퍼런스 있으면 첨부해주실 수 있을까요!!ㅎㅎ

2021-09-14 05:58 UTC, lagoJin commented on build.gradle
> +        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
https://github.com/android/sunflower/blob/main/build.gradle
파일은 임의로 만드셔도 되구, 요런방법처럼 project gradle에 ext로 묶어서 처리해도 좋을 것 같아요~

2021-09-15 01:39 UTC, Huijiny commented on build.gradle
> +        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.38.1'
감사해요! 참고해서 다시 올려놓을게요!

2021-09-15 04:21 UTC, lagoJin approved these changes
👍

2021-09-15 06:27 UTC, winter223 approved these changes
👍

2021-09-15 08:47 UTC, merged