WIP Music Fragment Navigation 에러
mash-up-kr/KKyuni_Android pull request #42
Opened 2021-10-02 16:29 UTC by Huijiny

## Issue

## Overview (Required)
-

## Links
-

## Screenshot
Before | After
:--: | :--:
<img src="" width="240" /> | <img src="" width="240" />

2021-10-02 17:15 UTC, koba0909 reviewed
중요해보이는거 2개만 리뷰 달아봤습니다.

2021-10-02 17:15 UTC, koba0909 commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicViewModel.kt
> +            Log.d("로그", videos.toString())
여기서 runCatching 혹은 try-catch문으로 에러 핸들링 들어가야할거 같아요.

2021-10-02 17:15 UTC, koba0909 commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +            viewModel = this@MusicAdapter.viewModel
여기서 바인드 해줄때 데이터가 안변할 수 있어요
executePendingBindings() 을 통해 강제적으로 데이터 변경을 시켜줘야 할거 같아요

[https://stackoverflow.com/questions/53043412/android-why-use-executependingbindings-in-recyclerview](https://stackoverflow.com/questions/53043412/android-why-use-executependingbindings-in-recyclerview)

2021-10-03 13:56 UTC, lagoJin requested changes
코멘트 내용만 확인해주면 좋을거 같은데, 마지막에 작업했던 Flow랑 BindingAdapter 반영해주면 좋겠어

2021-10-03 13:56 UTC, lagoJin commented on feature/music/data/build.gradle
>      implementation "androidx.core:core-ktx:$coreVersion"
data 모듈은 androidx 의존성이 필요없으니까 아래 세개 지우고, 추가로 coroutines 도 지워도 좋을거같아~

2021-10-03 13:56 UTC, lagoJin commented on feature/music/domain/build.gradle
> +    implementation "androidx.core:core-ktx:$coreVersion"
androidx 관련된 core라 필요없을거같아~

2021-10-03 13:56 UTC, lagoJin commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +    ListAdapter<VideoResponse, MusicViewHolder>(DiffUtilCallback) {
ListAdapter에 들어가는 데이터 타입을 Response가 아닌 도메인부터 사용하는 데이터 형으로 바꿔야할 것 같아~

2021-10-03 13:56 UTC, lagoJin commented on feature/music/presentation/src/main/res/layout/fragment_music.xml
> +            android:id="@+id/searchBar"
xml은 search_bar로 선언하는게 좋을것같아 데이터 바인딩이나 뷰바인딩으로 변경될때 자동으로 카멜케이스로 변경이되니까

2021-10-03 13:56 UTC, lagoJin commented on feature/music/presentation/build.gradle
> +    implementation(project(":feature:music:data"))
presentation은 data에 몰라야하니까 지우는게 좋을 것 같아~

2021-10-04 01:53 UTC, winter223 commented
다른 분들의 꼼꼼한 리뷰에 탑승..

2021-10-19 12:49 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +            viewModel = this@MusicAdapter.viewModel
참고자료까지 감사합니다!!

2021-10-19 12:50 UTC, Huijiny commented on feature/music/domain/build.gradle
> +    implementation "androidx.core:core-ktx:$coreVersion"
넵!

2021-10-19 12:51 UTC, Huijiny commented on feature/music/presentation/src/main/res/layout/fragment_music.xml
> +            android:id="@+id/searchBar"
아 글쿠나 네넵!

2021-10-19 12:55 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +    ListAdapter<VideoResponse, MusicViewHolder>(DiffUtilCallback) {
그 때 수정했었네요:)

2021-10-19 12:56 UTC, Huijiny commented on feature/music/presentation/build.gradle
> +    implementation(project(":feature:music:data"))
넵 감사합니다!

2021-10-19 14:14 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicViewModel.kt
> +            Log.d("로그", videos.toString())
넵! runCatching을 넣어봤는데, onSuccess에서 어떤 작업을 해야할지 모르겠어서 제외했습니다.
이렇게 해도 괜찮을까요?

2021-10-19 14:16 UTC, Huijiny commented on feature/music/data/build.gradle
>      implementation "androidx.core:core-ktx:$coreVersion"
androidx와 coroutines 지웠습니다!

2021-10-20 14:42 UTC, winter223 reviewed
깔-끔하네요

2021-10-20 14:42 UTC, ethan-223 commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +                }
`Lifecyle.State.STARTED` 이 안전할 것 같습니다

2021-10-20 14:42 UTC, winter223 commented on feature/music/domain/build.gradle
> +    }
android config 에 대한 외부 변수화를 해두었는데, 이를 사용하면 좋을 것 같습니다.

2021-10-20 14:42 UTC, ethan-223 commented on data/network/src/main/java/com/mashup/kkyuni/data/network/NetworkModule.kt
이 작업이 없으면 동작하지 않나요 ?
저는 없이도 잘 됐던 것 같은데 🤔

2021-10-21 12:41 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +                }
오호! 더 공부해보겠습니다!

2021-10-21 12:42 UTC, Huijiny commented on feature/music/domain/build.gradle
> +    }
참고하겠습니다!

2021-10-21 12:42 UTC, Huijiny commented on data/network/src/main/java/com/mashup/kkyuni/data/network/NetworkModule.kt
당시에는 안되서 추가해줬던 것 같은데, 다시 한 번 확인해보겠습니다!

2021-10-22 12:23 UTC, lagoJin requested changes

2021-10-22 12:23 UTC, lagoJin commented on feature/music/presentation/build.gradle
> +        minSdk 23
요기도 버전 대응~

2021-10-22 12:23 UTC, lagoJin commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +        override fun areItemsTheSame(oldItem: Video, newItem: Video) = oldItem == newItem
식별할 수 있는 고유값으로 넣어주면 더 좋을거같아요~

2021-10-22 12:23 UTC, lagoJin commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +        val adapter = MusicAdapter(musicViewModel)
```kotlin
binding.recycler.run {
   setLayoutmanager(LinearLayoutManager(context))
   adapter = adapter
}

어댑터는 viewCreated가 아닌 클래스 영역으로 빼는게 좋아요
뷰가 다시그려지게 되면 adapter도 다시 생성되서 기존 데이터나 스크롤상태등을 유지시켜주지 못합니다~

2021-10-24 23:02 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +                }
혹시 STARTED 가 더 안전할 것 같은 이유가 아래 진호님이 말씀해주신 것 처럼 뷰가 다시그려지게 되면 adapter도 다시 생성되기 때문에 어댑터 로직을 모두 Created밖으로 빼라는 것과 같은 맥락일까요:)?!

2021-10-24 23:29 UTC, Huijiny commented on data/network/src/main/java/com/mashup/kkyuni/data/network/NetworkModule.kt
Music 피처 모듈 data 레이어에 `com.squareup.moshi:moshi-kotlin-codege` 디펜던시를 추가해주지 않아서 발생한 일이더라구요! 
수정했습니다 :)!!

2021-10-24 23:47 UTC, Huijiny commented on feature/music/domain/build.gradle
> +    }
변경했습니다!!!! :)

2021-10-24 23:48 UTC, Huijiny commented on feature/music/presentation/build.gradle
> +        minSdk 23
성규님께서 말씀해주신 config 외부 변수 사용해서 music 모듈에 있는 모든 레이어에 반영했습니다!! :)

2021-10-25 00:09 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +        val adapter = MusicAdapter(musicViewModel)
감사합니다 진호님! 
수정했습니다!

2021-10-25 00:10 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +        override fun areItemsTheSame(oldItem: Video, newItem: Video) = oldItem == newItem
진호님! 어떤 부분을 말씀하시는지 이해를 못했는데 다시 한 번 설명해주실 수 있을까요?
oldItem, newItem 네이밍 말씀하시는걸까요?!

2021-10-25 00:12 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +                }
아니면 ViewCreated는 created가 된 이후인데 이곳에서 `Lifecycle.State.CREATED` 를 사용하게 되면 위험한걸까요?

2021-10-25 01:31 UTC, koba0909 requested changes

2021-10-25 01:31 UTC, koba0909 commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicViewModel.kt
> +            val videos = getMusic(query).items
여기에서 runCathing이 필요한곳은 getMusic(query).items 인거 같아요.

```kotlin
runCathing{
    getMusic(query).items
}.onSuccess{
    _videoList.emit(it)
}.onFailure { e ->
    Log.e(TAG, e.message)
}

```

2021-10-25 15:00 UTC, lagoJin approved these changes

2021-10-25 15:00 UTC, lagoJin commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +        override fun areItemsTheSame(oldItem: Video, newItem: Video) = oldItem == newItem
@Huijiny areItemsTemSame랑 areContentsTheSame이 동작하는 원리를 알면 이해하기가 좋을 거 같아요~

2021-10-26 06:17 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicAdapter.kt
> +        override fun areItemsTheSame(oldItem: Video, newItem: Video) = oldItem == newItem
넵! 감사합니다!! videoId값으로 비교하는걸로 수정했습니다!

2021-10-26 06:19 UTC, Huijiny commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicViewModel.kt
> +            val videos = getMusic(query).items
앗 넵. 참고하겠습니다!

2021-10-26 07:43 UTC, ethan-223 commented on feature/music/presentation/src/main/java/com/mashup/kkyuni/feature/music/presentation/MusicFragment.kt
> +                }
화면이 보여지고 있을 때에만 UI 를 갱신하는 게 리소스도 아끼고 혹시 모를 비정상 종료에 대처할 수 있습니다.
[참고](https://developer.android.com/topic/libraries/architecture/coroutines?hl=ko#restart)

2021-10-28 02:25 UTC, ethan-223 approved these changes

2021-10-28 03:12 UTC, koba0909 approved these changes

2021-10-28 03:19 UTC, merged