플레이 리스트 화면 구현
mash-up-kr/KKyuni_Android pull request #50
Opened 2021-10-09 14:10 UTC by koba0909

## Issue
- #32 

## Overview (Required)
- 캘린더 화면에서 달력 선택시 해당 하는 달의 모든 음악을 보여주는 플레이리스트 화면을 구현하였습니다.
- CalandarFragment: navigateToPlayListFragment() 통해 플레이리스트 화면 진입
- PlayListViewModel의 dateFlow에 새로운 Date(year, month)값이 들어오면 해당 값의 플레이 리스트 화면을 불러옵니다.
- 플레이 리스트 화면 특성상 모든 아이템을 갱신함으로 diffUtil사용할 필요 없을거 같아 RecyclerView.Adapter로 구현
- 더블 클릭방지를 위해 :core 에 onThrottleClick 추가
---
- 현재 year, month를 선택할 수 있게 하는 BottomSheetDialog는 아직 미구현으로 추후 별도의 pr로 올리겠습니다.
- 추후 구현이 필요한 부분은 TODO처리
- 플레이 리스트 불러올시 네트워크 에러 나면 별도의 정의된 동작이 없어 데이터가 없을 때 뷰를 넣어놨습니다. (디자인 논의 후 추후 수정)

## Links
-

## Screenshot
https://user-images.githubusercontent.com/61863078/136661071-84393872-6dac-4f55-9e40-a7987a810f5a.mp4

2021-10-09 14:33 UTC, lagoJin requested changes
아래 내용 확인 부탁드립니다~!
개인적인 의견인데 Flow를 쓰면 domain레이어로도 올려도 괜찮다고 생각합니다. android랑 의존성이 끊기기 때문에요,여기서 비즈니스로직 관련된 부분을 useCase에서 작업하는건 어떨까요?

ViewModel 에 로직이 많아지다보니 클린아키텍쳐 적용해서 분리된 부분이 조금 아쉽습니다 ㅜㅜ

core에 구현된 View쪽 관련된 바인딩어댑터는 widget 모듈로 내리는게 좋아보여요~

2021-10-09 14:33 UTC, lagoJin commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
버전 수정 원복해주세요~!

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/data/build.gradle
> +    compileSdk 31
버전 dependencies 에 있는걸로 대응해주세요~

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/data/src/main/java/com/mashup/kkyuni/playlist/data/di/PlayListDataModule.kt
> +    @InstallIn(ViewModelComponent::class)
요거는 별개로 repositoryModule로 구분하는게 좋아보입니다~

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/domain/build.gradle
> +        minSdk 23
버전 dependencies 대응해주세요~

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/presentation/build.gradle
> +        minSdk 23
dependencies 버전 대응만 수정해주세요

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListAdapter.kt
> +): RecyclerView.Adapter<RecyclerView.ViewHolder>() {
ListAdapter 사용은 안하는건가요 ?

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListFragment.kt
> +        val view = super.onCreateView(inflater, container, savedInstanceState)
onCreateView는 BindingFragment에서 처리해주는데, initView를 onviewCreated로 옮기고 지우는건 어떨까요?

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/domain/build.gradle
> +    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutineVersion"
domain레이어라 android coroutines말고 그냥 coroutines 들고오는게 더 좋지 않을까요 ?

2021-10-09 14:33 UTC, lagoJin commented on core/src/main/java/com/mashup/kkyuni/core/constant/Constant.kt
> +object Constant {
다른 피처 모듈에서 사용하지 않는다면, playlist모듈로 빼는게 좋아보여요~

2021-10-09 14:33 UTC, lagoJin commented on core/src/main/java/com/mashup/kkyuni/core/BindingAdapter.kt
> +@BindingAdapter(requireAll = false, value =["onThrottleClick", "throttleInterval"])
core쪽은 모든 모듈에 붙을 수 있으니까 presnetation레이어에서만 사용하니 widget으로 이동해야 할것 같슴니다

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListViewModel.kt
> +    private val _toastLiveData = MutableLiveData<String>()
Flow 사용하실거면 여기는 SharedFlow는 어떨까요

2021-10-09 14:33 UTC, lagoJin commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListBindingAdapter.kt
> +    if(!list.isNullOrEmpty()) {
```kotlin
list.isNotEmpty()
```

가 조금 더 보기 편하지 않을까유?

2021-10-12 00:47 UTC, ethan-223 approved these changes
라고진의 리뷰를 벗어나는 새로운 리뷰 포인트를 찾지 못했읍니다.
LGTM

2021-10-12 00:47 UTC, winter223 commented on feature/playlist/data/src/main/java/com/mashup/kkyuni/playlist/data/dto/PlayListDto.kt
> +    val diaryID: Int,
`@Keep` 은 난독화에서 제외시키기 위한 방법인가요 ?

2021-10-13 05:12 UTC, Huijiny commented on feature/playlist/data/src/main/java/com/mashup/kkyuni/playlist/data/dto/PlayListDto.kt
> +    val diaryID: Int,
저도 궁금함다

2021-10-13 08:53 UTC, koba0909 commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
원복했습니다~

2021-10-13 08:53 UTC, koba0909 commented on feature/playlist/data/build.gradle
> +    compileSdk 31
compile_sdk_version으로 수정했습니다~

2021-10-13 08:54 UTC, koba0909 commented on feature/playlist/domain/build.gradle
> +        minSdk 23
min_sdk_version으로 수정했습니다~

2021-10-13 08:54 UTC, koba0909 commented on feature/playlist/presentation/build.gradle
> +        minSdk 23
min_sdk_version으로 수정했습니다~

2021-10-13 08:55 UTC, koba0909 commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListAdapter.kt
> +): RecyclerView.Adapter<RecyclerView.ViewHolder>() {
Overview에 적어놓은바와 같이 해당 화면은 전체 아이템을 갱신하기 때문에

DiffUtil을 사용할 필요가 없을거 같아 Recyclerview.Adapter를 사용했습니다.

2021-10-13 08:57 UTC, koba0909 commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListFragment.kt
> +        val view = super.onCreateView(inflater, container, savedInstanceState)
onViewCreate에서 adapter를 다시 세팅해주면 화면 전환(가로 세로)시에 리스트 전체를 새로 그리는
이슈가 있다는 글을 본적이 있었는데 못찾겠네요..

앱에서 가로모드를 지원하지 않아서 onViewCreated안에 선언해도 상관 없겠네요

2021-10-13 08:58 UTC, koba0909 commented on core/src/main/java/com/mashup/kkyuni/core/constant/Constant.kt
> +object Constant {
해당 object는 추후 일기 작성 피처 모듈에서 사용할 예정이라 app 모듈로 빼놓은거였어요~

2021-10-13 08:58 UTC, koba0909 commented on core/src/main/java/com/mashup/kkyuni/core/BindingAdapter.kt
> +@BindingAdapter(requireAll = false, value =["onThrottleClick", "throttleInterval"])
widget으로 이동시켜놓을게요~!

2021-10-13 08:59 UTC, koba0909 commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListViewModel.kt
> +    private val _toastLiveData = MutableLiveData<String>()
databinding에선 아직 SharedFlow를 지원안하지 않나요?

2021-10-13 09:07 UTC, koba0909 commented on feature/playlist/domain/build.gradle
> +    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutineVersion"
android 대신 core 가져왔어요~
말씀해준 수정 포인트 맞나요?

2021-10-13 09:16 UTC, koba0909 commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListBindingAdapter.kt
> +    if(!list.isNullOrEmpty()) {
viewModel단에서 저 리스트를 flow에서 livedata로 변환시키는데 처음에 null 값이 넘어와서
list를 nullable로 받을 수 밖에 없었어요.

2021-10-13 09:16 UTC, koba0909 commented on core/src/main/java/com/mashup/kkyuni/core/BindingAdapter.kt
> +@BindingAdapter(requireAll = false, value =["onThrottleClick", "throttleInterval"])
이동시켰습니다~

2021-10-13 09:23 UTC, koba0909 commented on feature/playlist/data/src/main/java/com/mashup/kkyuni/playlist/data/dto/PlayListDto.kt
> +    val diaryID: Int,
네 난독화 제외시키기 위해서 사용했어요.
[주석으로 코드 검사 개선](https://developer.android.com/studio/write/annotations?hl=ko#nullability-analysis)

2021-10-13 10:03 UTC, koba0909 commented on feature/playlist/data/src/main/java/com/mashup/kkyuni/playlist/data/di/PlayListDataModule.kt
> +    @InstallIn(ViewModelComponent::class)
개인적으로 작업할땐 멀티모듈을 사용하지 않아서 di를 presenter, domain, data 단으로 나눠서 관리했었는데
멀티모듈을 적용하니 그럴 필요가 없겠군여 나누도록 할게요~

2021-10-13 10:07 UTC, koba0909 commented on feature/playlist/data/src/main/java/com/mashup/kkyuni/playlist/data/di/PlayListDataModule.kt
> +    @InstallIn(ViewModelComponent::class)
NetworkModule, RepositoryModule 둘로 나누었어요~

2021-10-15 12:36 UTC, lagoJin commented on feature/playlist/domain/build.gradle
> +    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutineVersion"
맞습니다~

2021-10-15 12:39 UTC, lagoJin commented on feature/playlist/presentation/src/main/java/com/mashup/kkyuni/feature/playlist/presentation/PlayListViewModel.kt
> +    private val _toastLiveData = MutableLiveData<String>()
넹 그 부분은 놓친것같습니다~ 확인해보겠습니다~

2021-10-15 12:40 UTC, lagoJin approved these changes

2021-10-15 12:58 UTC, merged